<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->delete();

        $password = Hash::make('12345678');

        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Tuan Anh',
                'email' => 'giamdoc@gmail.com',
                'email_verified_at' => '2026-07-01 08:05:12',
                'password' => $password,
                'role_id' => 1,
                'department_id' => null,
                'avatar_path' => null,
                'is_active' => true,
                'remember_token' => null,
                'created_at' => '2026-07-01 08:05:12',
                'updated_at' => '2026-07-18 17:21:44',
            ],
            [
                'id' => 2,
                'name' => 'Hoang Thi Em',
                'email' => 'em.hoang@mobifone.vn',
                'email_verified_at' => '2026-07-01 08:19:37',
                'password' => $password,
                'role_id' => 2,
                'department_id' => 1,
                'avatar_path' => null,
                'is_active' => true,
                'remember_token' => null,
                'created_at' => '2026-07-01 08:19:37',
                'updated_at' => '2026-07-17 16:40:22',
            ],
            [
                'id' => 3,
                'name' => 'Nguyen Chi Vinh',
                'email' => 'vinh@mobifone.vn',
                'email_verified_at' => '2026-07-01 08:34:58',
                'password' => $password,
                'role_id' => 2,
                'department_id' => 2,
                'avatar_path' => null,
                'is_active' => true,
                'remember_token' => null,
                'created_at' => '2026-07-01 08:34:58',
                'updated_at' => '2026-07-16 15:08:31',
            ],
            [
                'id' => 4,
                'name' => 'Tran Phuoc Khang',
                'email' => 'khang2005@gmail.com',
                'email_verified_at' => '2026-07-01 09:02:21',
                'password' => $password,
                'role_id' => 2,
                'department_id' => 3,
                'avatar_path' => null,
                'is_active' => true,
                'remember_token' => null,
                'created_at' => '2026-07-01 09:02:21',
                'updated_at' => '2026-07-19 10:13:45',
            ],
            [
                'id' => 5,
                'name' => 'Tuyet Kha',
                'email' => 'kha2005@gmail.com',
                'email_verified_at' => '2026-07-02 07:52:10',
                'password' => $password,
                'role_id' => 3,
                'department_id' => 1,
                'avatar_path' => null,
                'is_active' => true,
                'remember_token' => null,
                'created_at' => '2026-07-02 07:52:10',
                'updated_at' => '2026-07-18 13:27:09',
            ],
            [
                'id' => 6,
                'name' => 'Be Ngoan',
                'email' => 'ngoan2005@gmail.com',
                'email_verified_at' => '2026-07-02 08:16:43',
                'password' => $password,
                'role_id' => 3,
                'department_id' => 1,
                'avatar_path' => null,
                'is_active' => true,
                'remember_token' => null,
                'created_at' => '2026-07-02 08:16:43',
                'updated_at' => '2026-07-18 14:03:58',
            ],
            [
                'id' => 7,
                'name' => 'Hoang Yem',
                'email' => 'hoangyem2005@gmail.com',
                'email_verified_at' => '2026-07-02 08:41:25',
                'password' => $password,
                'role_id' => 3,
                'department_id' => 1,
                'avatar_path' => null,
                'is_active' => true,
                'remember_token' => null,
                'created_at' => '2026-07-02 08:41:25',
                'updated_at' => '2026-07-17 11:35:16',
            ],
            [
                'id' => 8,
                'name' => 'Phuc Nguyen',
                'email' => 'phuc2005@gmail.com',
                'email_verified_at' => '2026-07-03 09:11:06',
                'password' => $password,
                'role_id' => 3,
                'department_id' => 2,
                'avatar_path' => null,
                'is_active' => true,
                'remember_token' => null,
                'created_at' => '2026-07-03 09:11:06',
                'updated_at' => '2026-07-18 08:49:12',
            ],
            [
                'id' => 9,
                'name' => 'Nhan Tran',
                'email' => 'nhan2005@gmail.com',
                'email_verified_at' => '2026-07-03 09:38:44',
                'password' => $password,
                'role_id' => 3,
                'department_id' => 2,
                'avatar_path' => null,
                'is_active' => true,
                'remember_token' => null,
                'created_at' => '2026-07-03 09:38:44',
                'updated_at' => '2026-07-19 09:52:07',
            ],
            [
                'id' => 10,
                'name' => 'Sen Le',
                'email' => 'sen2005@gmail.com',
                'email_verified_at' => '2026-07-03 10:04:33',
                'password' => $password,
                'role_id' => 3,
                'department_id' => 2,
                'avatar_path' => null,
                'is_active' => true,
                'remember_token' => null,
                'created_at' => '2026-07-03 10:04:33',
                'updated_at' => '2026-07-17 15:44:29',
            ],
            [
                'id' => 11,
                'name' => 'Kha Tran',
                'email' => 'kha.tran@mobifone.vn',
                'email_verified_at' => '2026-07-04 08:23:51',
                'password' => $password,
                'role_id' => 3,
                'department_id' => 3,
                'avatar_path' => null,
                'is_active' => true,
                'remember_token' => null,
                'created_at' => '2026-07-04 08:23:51',
                'updated_at' => '2026-07-20 10:18:36',
            ],
            [
                'id' => 12,
                'name' => 'Khoi Pham',
                'email' => 'khoi@mobifone.vn',
                'email_verified_at' => '2026-07-04 08:57:19',
                'password' => $password,
                'role_id' => 3,
                'department_id' => 3,
                'avatar_path' => null,
                'is_active' => true,
                'remember_token' => null,
                'created_at' => '2026-07-04 08:57:19',
                'updated_at' => '2026-07-19 16:31:08',
            ],
        ]);
    }
}
